### ISSUE TITLE
Right sidebar

### ISSUE THREAD

**Issue by robciucioan** [cristianraiber/regina-lite#3]

**Comment by robciucioan** [comment]
@cristianraiber, aici trebuie doar să mai stilizez calendarul.

**Comment by cristianraiber** [comment]
:+1:

**Comment by robciucioan** [comment]
@cristianraiber, 99% am implementat același stil ca-n HTML, doar că nu am reușit să schimb săgețile calendarului.

Verifică, te rog, să vezi dacă e ok.
